import type { CalculatorId } from './types'
import type { UnitKind } from './units'

export interface FieldDefinition { key: string; label: string; symbol: string; defaultValue: number; min?: number; max?: number; step?: number; kind: UnitKind; fixedUnit?: string; help: string }
export interface CalculatorDefinition { id: CalculatorId; name: string; shortName: string; eyebrow: string; description: string; equation: string; assumptions: string[]; fields: FieldDefinition[]; resultLabels: Record<string, string> }

const gas = (mach = 2): FieldDefinition[] => [
  { key: 'mach', label: 'Mach number', symbol: 'M₁', defaultValue: mach, min: 0.01, step: 0.05, kind: 'none', help: 'Upstream flow speed divided by local speed of sound.' },
  { key: 'gamma', label: 'Specific heat ratio', symbol: 'γ', defaultValue: 1.4, min: 1.01, max: 2, step: 0.01, kind: 'none', help: '1.4 is typical for air near room temperature.' },
]

export const calculators: CalculatorDefinition[] = [
  { id: 'isentropic', name: 'Isentropic flow', shortName: 'Isentropic', eyebrow: 'Area · State ratios', description: 'Relate Mach number to stagnation properties and the critical-area ratio for a calorically perfect gas.', equation: 'T₀/T = 1 + (γ−1)M²/2', assumptions: ['Steady, adiabatic, reversible flow', 'Calorically perfect gas with constant γ'], fields: gas(2), resultLabels: { t0_t: 'T₀ / T', p0_p: 'p₀ / p', rho0_rho: 'ρ₀ / ρ', area_ratio: 'A / A*' } },
  { id: 'normal-shock', name: 'Normal shock', shortName: 'Normal shock', eyebrow: 'Compression · Losses', description: 'Resolve the downstream state and stagnation-pressure loss across a normal shock.', equation: 'M₂² = [1 + (γ−1)M₁²/2] / [γM₁² − (γ−1)/2]', assumptions: ['One-dimensional, adiabatic shock', 'Upstream Mach number must be supersonic'], fields: gas(2), resultLabels: { mach_2: 'M₂', p2_p1: 'p₂ / p₁', t2_t1: 'T₂ / T₁', rho2_rho1: 'ρ₂ / ρ₁', p02_p01: 'p₀₂ / p₀₁' } },
  { id: 'oblique-shock', name: 'Oblique shock', shortName: 'Oblique shock', eyebrow: 'Wedges · Two branches', description: 'Solve attached weak and strong shock branches for a compression corner.', equation: 'tan θ = 2 cot β · (M₁² sin²β − 1) / [M₁²(γ + cos 2β) + 2]', assumptions: ['Planar attached shock', 'A detached-shock warning is returned above θmax'], fields: [...gas(2.5), { key: 'theta_deg', label: 'Deflection angle', symbol: 'θ', defaultValue: 15, min: 0.01, max: 89, step: 0.5, kind: 'none', fixedUnit: 'deg', help: 'Flow turning angle at the compression corner.' }], resultLabels: { beta_weak_deg: 'β weak', beta_strong_deg: 'β strong', theta_max_deg: 'θ max', mach_2_weak: 'M₂ weak', mach_2_strong: 'M₂ strong', p2_p1_weak: 'p₂/p₁ weak', p2_p1_strong: 'p₂/p₁ strong', p02_p01_weak: 'p₀₂/p₀₁ weak', p02_p01_strong: 'p₀₂/p₀₁ strong' } },
  { id: 'prandtl-meyer', name: 'Prandtl–Meyer expansion', shortName: 'Prandtl–Meyer', eyebrow: 'Expansion fan', description: 'Find the downstream Mach number after an isentropic supersonic turn.', equation: 'ν(M₂) = ν(M₁) + θ', assumptions: ['Supersonic inlet', 'Centered, isentropic expansion fan'], fields: [...gas(2), { key: 'theta_deg', label: 'Expansion angle', symbol: 'θ', defaultValue: 10, min: 0.01, max: 89, step: 0.5, kind: 'none', fixedUnit: 'deg', help: 'Positive turn away from the flow.' }], resultLabels: { mach_2: 'M₂', nu_1_deg: 'ν₁', nu_2_deg: 'ν₂', mach_angle_1_deg: 'μ₁', mach_angle_2_deg: 'μ₂' } },
  { id: 'fanno', name: 'Fanno flow', shortName: 'Fanno flow', eyebrow: 'Duct friction', description: 'Track Mach number change through a constant-area adiabatic duct with wall friction.', equation: '4fL/D = F(M₁) − F(M₂)', assumptions: ['Constant-area adiabatic duct', 'Darcy-style 4fL/D convention used here'], fields: [...gas(0.5), { key: 'friction_factor', label: 'Friction factor', symbol: 'f', defaultValue: 0.005, min: 0, step: 0.001, kind: 'none', help: 'Fanning friction factor used in 4fL/D.' }, { key: 'length_m', label: 'Duct length', symbol: 'L', defaultValue: 5, min: 0, step: 0.1, kind: 'length', help: 'Axial duct length.' }, { key: 'diameter_m', label: 'Hydraulic diameter', symbol: 'D', defaultValue: 0.4, min: 0.0001, step: 0.01, kind: 'length', help: 'Hydraulic diameter of the passage.' }], resultLabels: { mach_2: 'M₂', fanno_available: 'F(M₁)', friction_consumed: '4fL / D', remaining_to_sonic: 'Remaining to M=1' } },
  { id: 'rayleigh', name: 'Rayleigh flow', shortName: 'Rayleigh flow', eyebrow: 'Heat addition', description: 'Resolve the downstream state in constant-area frictionless flow with heat transfer.', equation: 'T₀₂ = T₀₁ + q / cₚ', assumptions: ['Constant-area, frictionless flow', 'Positive q adds heat; negative q removes heat'], fields: [...gas(1.4), { key: 'temperature_k', label: 'Static temperature', symbol: 'T₁', defaultValue: 300, min: 0.01, step: 1, kind: 'temperature', help: 'Upstream static temperature.' }, { key: 'cp_j_kgk', label: 'Specific heat', symbol: 'cₚ', defaultValue: 1005, min: 0.01, step: 1, kind: 'specificHeat', help: 'Constant-pressure specific heat.' }, { key: 'heat_j_kg', label: 'Specific heat transfer', symbol: 'q', defaultValue: -63277, step: 100, kind: 'heat', help: 'Positive for heat addition, negative for removal.' }], resultLabels: { mach_2: 'M₂', stagnation_temperature_1_k: 'T₀₁', stagnation_temperature_2_k: 'T₀₂', p2_p1: 'p₂ / p₁', t2_t1: 'T₂ / T₁', rho2_rho1: 'ρ₂ / ρ₁' } },
  { id: 'natural-convection', name: 'Natural convection', shortName: 'Natural convection', eyebrow: 'Buoyancy · Similarity', description: 'Calculate Rayleigh and Grashof numbers from surface, ambient, and fluid properties.', equation: 'Ra = gβΔTL³ / (αν)', assumptions: ['Properties evaluated at film temperature', 'Ideal-gas thermal expansion coefficient β = 1/Tf'], fields: [{ key: 'surface_temperature_k', label: 'Surface temperature', symbol: 'Tₛ', defaultValue: 363.15, min: 0.01, step: 1, kind: 'temperature', help: 'Absolute surface temperature.' }, { key: 'ambient_temperature_k', label: 'Ambient temperature', symbol: 'T∞', defaultValue: 303.15, min: 0.01, step: 1, kind: 'temperature', help: 'Absolute free-stream temperature.' }, { key: 'thermal_diffusivity_m2_s', label: 'Thermal diffusivity', symbol: 'α', defaultValue: 0.00002808, min: 1e-12, step: 0.000001, kind: 'none', fixedUnit: 'm²/s', help: 'Thermal diffusivity at film temperature.' }, { key: 'kinematic_viscosity_m2_s', label: 'Kinematic viscosity', symbol: 'ν', defaultValue: 0.00001895, min: 1e-12, step: 0.000001, kind: 'none', fixedUnit: 'm²/s', help: 'Kinematic viscosity at film temperature.' }, { key: 'characteristic_length_m', label: 'Characteristic length', symbol: 'L', defaultValue: 0.3125, min: 0.0001, step: 0.01, kind: 'length', help: 'Geometry-dependent characteristic length.' }], resultLabels: { film_temperature_k: 'Film temperature', rayleigh: 'Rayleigh number', grashof: 'Grashof number' } },
]

export const calculatorById = Object.fromEntries(calculators.map(item => [item.id, item])) as Record<CalculatorId, CalculatorDefinition>
export const defaultInputs = (definition: CalculatorDefinition) => Object.fromEntries(definition.fields.map(field => [field.key, field.defaultValue]))

